# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ZSZOhgmAvsczbMh1DJ2bFGJmaNA2s_i
"""

import streamlit as st
import pandas as pd
import json
import os
import base64
from datetime import datetime, timedelta, timezone
from PIL import Image as PILImage
import vertexai
from vertexai.generative_models import GenerativeModel, Image, GenerationConfig

# --- 1. INITIALIZATION & CONFIG ---
# This looks for the ID in your Streamlit Secrets dashboard
if "PROJECT_ID" in st.secrets:
    PROJECT_ID = st.secrets["PROJECT_ID"]
else:
    PROJECT_ID = "your-actual-id-here" # You can put it here if your GitHub repo is PRIVATE

vertexai.init(project=PROJECT_ID, location="us-central1")


# Note: Using gemini-2.5-pro as it is the current stable high-reasoning model
model = GenerativeModel("gemini-2.5-pro")

st.set_page_config(page_title="AI Circuit Tutor", layout="centered")

# --- 2. SESSION STATE MANAGEMENT ---
# Streamlit reruns the script on every click. We use session_state to "remember"
# the conversation and images during the Socratic rounds.
if 'socratic_round' not in st.session_state:
    st.session_state.socratic_round = 0
if 'chat_history' not in st.session_state:
    st.session_state.chat_history = ""
if 'analysis_done' not in st.session_state:
    st.session_state.analysis_done = False
if 'current_analysis' not in st.session_state:
    st.session_state.current_analysis = {}

# --- 3. UI LAYOUT ---
st.title("🔌 AI Circuit Diagnostic Station")

with st.sidebar:
    st.header("Student Setup")
    student_number = st.text_input("Student Number (1-70)", placeholder="e.g. 42")
    task_number = st.number_input("Task Number", min_value=1, max_value=10, value=1)
    option_choice = st.radio("Debug Mode", ["1: Direct Debug", "2: Socratic Debug"])

    if st.button("Reset Session"):
        for key in st.session_state.keys():
            del st.session_state[key]
        st.rerun()

# --- 4. IMAGE CAPTURE ---
# This replaces the Javascript take_photo function from Colab
img_file = st.camera_input("Capture your breadboard circuit")

# --- 5. CORE LOGIC ---
if img_file and student_number:
    # Prepare paths (matching your data2 structure)
    base_folder = "data2"
    ref_image_name = f"circuit-{task_number}.jpg"
    ref_path = os.path.join(base_folder, ref_image_name)

    if not os.path.exists(ref_path):
        st.error(f"Reference image {ref_image_name} not found in '{base_folder}' folder.")
    else:
        # Load images for AI
        schematic_img_ai = Image.load_from_file(ref_path)
        student_img_bytes = img_file.getvalue()
        student_img_ai = Image.from_bytes(student_img_bytes)

        # --- MODE 1: DIRECT DEBUG ---
        if "1" in option_choice and not st.session_state.analysis_done:
            with st.spinner("Analyzing circuit..."):
                mode_text = "Direct Debug Mode: Provide concise diagnosis and correction."

                # YOUR ORIGINAL PROMPT
                prompt = f"""
                You are a Senior Electronic Systems Diagnostic Engineer. Your task is to validate a student's breadboard circuit (Image 2) against a reference schematic (Image 1).
                Mode: {mode_text}
                [OUTPUT FORMAT - JSON ONLY]
                {{
                  "schematic_netlist": "...",
                  "student_netlist": "...",
                  "match_status": "CORRECT" or "INCORRECT",
                  "error_analysis": "...",
                  "remediation_hints": "...",
                  "follow_up_QA": "..."
                }}
                """

                response = model.generate_content(
                    [prompt, schematic_img_ai, student_img_ai],
                    generation_config=GenerationConfig(response_mime_type="application/json")
                )
                st.session_state.current_analysis = json.loads(response.text)
                st.session_state.analysis_done = True

        # --- MODE 2: SOCRATIC DEBUG (The Loop) ---
        elif "2" in option_choice and not st.session_state.analysis_done:
            if st.session_state.socratic_round < 3:
                st.subheader(f"Socratic Round {st.session_state.socratic_round + 1} of 3")

                # Generate Question
                q_prompt = f"""
                Socratic Debug Mode, Round {st.session_state.socratic_round + 1}.
                Compare Image 1 (Reference) and Image 2 (Student).
                Ask ONE guiding question only to help the student find their own error. Do not give the answer.
                """
                q_response = model.generate_content([q_prompt, schematic_img_ai, student_img_ai])
                ai_question = q_response.text

                st.info(f"**AI Question:** {ai_question}")

                # Student Answer Input
                with st.form(key=f"round_{st.session_state.socratic_round}"):
                    student_ans = st.text_input("Your Answer:")
                    submit_ans = st.form_submit_button("Submit Answer")

                    if submit_ans and student_ans:
                        st.session_state.chat_history += f"Q: {ai_question}\nA: {student_ans}\n"
                        st.session_state.socratic_round += 1
                        st.rerun()

            else:
                # Final Diagnosis after 3 rounds
                with st.spinner("Finalizing analysis..."):
                    final_prompt = f"""
                    Provide final diagnosis and remediation hints after 3 rounds of Socratic dialogue.
                    Student History: {st.session_state.chat_history}
                    [OUTPUT FORMAT - JSON ONLY]
                    {{
                      "schematic_netlist": "...",
                      "student_netlist": "...",
                      "match_status": "CORRECT" or "INCORRECT",
                      "error_analysis": "...",
                      "remediation_hints": "...",
                      "follow_up_QA": "{st.session_state.chat_history}"
                    }}
                    """
                    final_res = model.generate_content(
                        [final_prompt, schematic_img_ai, student_img_ai],
                        generation_config=GenerationConfig(response_mime_type="application/json")
                    )
                    st.session_state.current_analysis = json.loads(final_res.text)
                    st.session_state.analysis_done = True

        # --- 6. DISPLAY RESULTS & SAVE ---
        if st.session_state.analysis_done:
            data = st.session_state.current_analysis

            st.divider()
            st.subheader(f"Result: {data['match_status']}")

            col1, col2 = st.columns(2)
            with col1:
                st.markdown("**Analysis**")
                st.write(data['error_analysis'])
            with col2:
                st.markdown("**Hint**")
                st.info(data['remediation_hints'])

            # CSV Logging Logic
            if st.button("Finalize and Save Entry"):
                now_hkt = datetime.now(timezone.utc) + timedelta(hours=8)
                timestamp_str = now_hkt.strftime('%Y_%m_%d__%H_%M_%S')

                new_row = {
                    "Student Number": student_number,
                    "Time (HKT)": now_hkt.strftime('%Y-%m-%d %H:%M:%S'),
                    "Task": task_number,
                    "Result": data['match_status'],
                    "Analysis": data['error_analysis'],
                    "Option": option_choice,
                    "History": data.get("follow_up_QA", "")
                }

                # In Streamlit Cloud, we usually save to a DataFrame then allow download
                # or connect to a Google Sheet. For now, we'll show success.
                st.success(f"Entry for Student {student_number} recorded successfully!")
                st.balloons()

                # Provide a download button for the data
                df_to_save = pd.DataFrame([new_row])
                csv = df_to_save.to_csv(index=False).encode('utf-8')
                st.download_button("Download Record CSV", csv, f"record_{student_number}.csv", "text/csv")

