# -*- coding: utf-8 -*-
import streamlit as st
import streamlit.components.v1 as components
import json
import pandas as pd
from google import genai
from google.genai import types
from google.oauth2 import service_account

# --- 1. INITIALIZATION & CONFIG ---
st.set_page_config(page_title="Socratic Breadboard Simulator", layout="wide")
MODEL_ID = "gemini-3.1-pro-preview"

# Initialize Session State
if "tokens" not in st.session_state: st.session_state.tokens = 10
if "feedback_history" not in st.session_state: st.session_state.feedback_history = []

@st.cache_resource
def get_ai_client():
    if "gcp_service_account" in st.secrets:
        creds_info = st.secrets["gcp_service_account"]
        scopes = ["https://www.googleapis.com/auth/cloud-platform"]
        credentials = service_account.Credentials.from_service_account_info(creds_info, scopes=scopes)
        return genai.Client(vertexai=True, project=creds_info["project_id"], location="global", credentials=credentials)
    return None

client = get_ai_client()

# --- 2. SIDEBAR (The Orchestration Layer) ---
with st.sidebar:
    st.title("🔌 Circuit Mission")
    st.metric("Budget (Tokens)", st.session_state.tokens)
    st.info("Goal: Build a series circuit with a Battery, Resistor, and LED.")
    
    if st.button("🔄 Reset Simulator"):
        st.session_state.tokens = 10
        st.session_state.feedback_history = []
        st.rerun()

    st.markdown("---")
    st.write("### AI Feedback Log")
    for msg in st.session_state.feedback_history[-3:]:
        st.caption(f"🤖 {msg}")

# --- 3. THE BREADBOARD SIMULATOR (JavaScript/SVG) ---
# This block handles the real-time interaction and "Struggle Detection" data
simulator_html = """
<!DOCTYPE html>
<html>
<head>
    <style>
        #bb-container { position: relative; width: 850px; height: 500px; background: #eee; border-radius: 10px; overflow: hidden; border: 3px solid #333; }
        .breadboard { position: absolute; top: 50px; left: 100px; width: 600px; height: 350px; background: #fff; border: 1px solid #ddd; display: grid; grid-template-columns: repeat(30, 1fr); padding: 10px; gap: 5px; }
        .hole { width: 12px; height: 12px; background: #ddd; border-radius: 50%; cursor: pointer; }
        .hole:hover { background: #ffaa00; }
        .component { position: absolute; padding: 10px; border: 2px solid #000; border-radius: 5px; cursor: move; z-index: 10; font-weight: bold; font-size: 12px; }
        #battery { top: 50px; left: 10px; background: #ff4b4b; color: white; }
        #resistor { top: 150px; left: 10px; background: #f0f2f6; }
        #led { top: 250px; left: 10px; background: #1a73e8; color: white; }
        svg { position: absolute; top: 0; left: 0; width: 100%; height: 100%; pointer-events: none; }
        #controls { position: absolute; bottom: 10px; right: 10px; }
        button { padding: 10px 20px; background: #28a745; color: white; border: none; border-radius: 5px; cursor: pointer; font-weight: bold; }
    </style>
</head>
<body>
    <div id="bb-container">
        <svg id="wires"></svg>
        <div class="component" id="battery" draggable="true">9V BATTERY</div>
        <div class="component" id="resistor" draggable="true">RESISTOR (220Ω)</div>
        <div class="component" id="led" draggable="true">LED (RED)</div>
        
        <div class="breadboard" id="board">
            <!-- Holes generated by JS -->
        </div>

        <div id="controls">
            <button onclick="sendTopology()">✅ Analyze My Circuit</button>
        </div>
    </div>

    <script>
        const board = document.getElementById('board');
        const holes = [];
        let connections = []; // Track wire nodes

        // Generate Breadboard Holes (simplified grid)
        for (let i = 0; i < 300; i++) {
            const hole = document.createElement('div');
            hole.className = 'hole';
            hole.id = 'h-' + i;
            hole.onclick = () => handleHoleClick(i);
            board.appendChild(hole);
            holes.push(hole);
        }

        let firstHole = null;
        function handleHoleClick(id) {
            if (firstHole === null) {
                firstHole = id;
                holes[id].style.background = 'blue';
            } else {
                drawWire(firstHole, id);
                connections.push({from: firstHole, to: id});
                holes[firstHole].style.background = '#ddd';
                firstHole = null;
            }
        }

        function drawWire(h1, h2) {
            const svg = document.getElementById('wires');
            const hole1 = document.getElementById('h-' + h1).getBoundingClientRect();
            const hole2 = document.getElementById('h-' + h2).getBoundingClientRect();
            const container = document.getElementById('bb-container').getBoundingClientRect();

            const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
            line.setAttribute('x1', hole1.left - container.left + 6);
            line.setAttribute('y1', hole1.top - container.top + 6);
            line.setAttribute('x2', hole2.left - container.left + 6);
            line.setAttribute('y2', hole2.top - container.top + 6);
            line.setAttribute('stroke', '#333');
            line.setAttribute('stroke-width', '3');
            svg.appendChild(line);
        }

        function sendTopology() {
            // Package the data to send back to Streamlit
            const data = {
                type: "ANALYZE_REQUEST",
                connections: connections,
                timestamp: Date.now()
            };
            window.parent.postMessage({
                isstreamlit: true,
                type: "streamlit:setComponentValue",
                value: data
            }, "*");
        }
    </script>
</body>
</html>
"""

# --- 4. STREAMLIT BACKEND & SOCRATIC LOGIC ---
st.subheader("🛠️ Real-Time Construction Sandbox")
# The simulator returns data through this component
result = components.html(simulator_html, height=520)

# Process the AI Scan
if result:
    # This logic only runs when the "Analyze" button in JS is clicked
    st.session_state.tokens -= 1
    
    with st.spinner("Analyzing your connection logic..."):
        # Format the topology for Gemini
        topology_desc = json.dumps(result.get("connections", []))
        
        # Socratic Scaffolding Prompt
        socratic_prompt = f"""
        You are a Socratic Engineering Tutor for P4-S3 students.
        The student is building a series circuit. 
        Current Topology (Hole IDs): {topology_desc}
        
        Your Goal:
        1. Check if the Battery, Resistor, and LED form a closed loop.
        2. Identify the SPECIFIC struggle (e.g., Short circuit, Open circuit, or Reversed Polarity).
        3. DO NOT give the answer. Use Socratic Scaffolding.
        4. Ask a question that forces them to move from 'Behavioral' (clicking) to 'Cognitive' (logical thinking) engagement.
        5. If they have used many tokens and are still failing, give a slightly more direct 'Spatial Hint' using the hole IDs.
        """
        
        if client:
            try:
                response = client.models.generate_content(model=MODEL_ID, contents=socratic_prompt)
                ai_hint = response.text
                st.session_state.feedback_history.append(ai_hint)
                
                # Display the hint prominently
                st.markdown(f"### 🤖 AI Guidance")
                st.info(ai_hint)
            except Exception as e:
                st.error(f"AI Analysis Error: {e}")

# --- 5. EDUCATIONAL FRAMEWORK CONTEXT (For your paper) ---
with st.expander("ℹ️ Pedagogical Framework (ICAP Model)"):
    st.write("""
    - **Active**: Dragging components and drawing wires.
    - **Constructive**: Explaining the circuit logic to the AI via the 'Analyze' button.
    - **Interactive**: Responding to the Socratic hints to debug the circuit.
    - **Game Theory**: The token budget discourages random clicking and forces students to value their 'moves'.
    """)
